### ISSUE TITLE
dynamodb querying

### ISSUE THREAD

**Issue by DavisFrench** [PriceGuyS/pg-backend#1]
For a brief explanation of how the schema keys work https://aws.amazon.com/blogs/database/choosing-the-right-dynamodb-partition-key/

The issue seems to be that a query absolutely requires the partition key, which is supposed to be unique (or at least fairly unique). The only allowed operation for the partition key in the query is "=". This means that if we used id as the partition key we would have to query using oddly specific id's like "889617888928". This obviously is not intuitive or helpful for user side querying. We need to come up with a solution.

**Comment by DavisFrench** [comment]
on test table 6 I have the inputQuery as the partition key and the id as the hash key. Queries now return everything. However since the partition key can only use '=' the string has to exactly match. For example, "Super Mario 64" would return all the "Super Mario 64" results, but "Mario" wouldn't return anything. This is something we need to consider.

**Comment by JohnLe01** [comment]
I believe we have resolved this. Good to close?

**Comment by DavisFrench** [comment]
Yeah. I'm still a little unhappy how the query has to match exactly, but I guess we could do a drop down menu based on what they are typing maybe

**Comment by JohnLe01** [comment]
@DavisFrench Heres an idea: what if we query all of the the game titles we have in the database and store them in a list, and then do a partial filter on the list when the user is trying to search/filter for something?
