### ISSUE TITLE
Fix initial import

### ISSUE THREAD

**Issue by JohnLe01** [PriceGuyS/pg-backend#6]
Currently, there is a slight problem with importing the queried data into the database. It appears that there has to be a delay between generating the data into json and importing that data into the database. Sometimes, there might not be an existing table and the import fails. 

- [x] Investigate delay between data generation and importing
- [ ] Execute fix

**Comment by DavisFrench** [comment]
I have implemented a 15 second sleep between table creation and population, however an error sometimes occurs saying that "put_item" is not available. Need to search for a way to check if table has successfully been created.

**Comment by JohnLe01** [comment]
Seemingly. having the wrapper as well as a maximum retry limit fixes the put_item issue. Successfully imports with the small list. Need to further test with larger list

**Comment by JohnLe01** [comment]
Test with larger list successful. See additional comments in #9
